### ISSUE TITLE
Add git installation instructions

### ISSUE THREAD

**Issue by korenmiklos** [korenmiklos/2020-08-23-eea#14]
Reuse the html section in the previous version of the repo

**Comment by korenmiklos** [comment]
Somewhere around here https://github.com/korenmiklos/2020-08-23-eea/blame/gh-pages/index.md#L232
Can be copied from here https://github.com/kulibraries/2020-07-24-ku-online/blob/gh-pages/_includes/swc/setup.html

**Comment by kiss-oliver** [comment]
closed by ee5c85b6302900392282a9ac46ae505db7fd877e #
