### ISSUE TITLE
Check Stata installation instructions

### ISSUE THREAD

**Issue by korenmiklos** [korenmiklos/2020-08-23-eea#15]
Make sure they are accurate with our current access. Version numbers etc. Do not include any of our secrets, these will be communicated to learners one-by-one if they need it.

**Comment by andrasvereckei** [comment]
Updated Stata installation guide for the 3 OS. 
@korenmiklos Why the Update index.md changed? 
When do I have to edit the episodes directly?

**Comment by korenmiklos** [comment]
These are workshop specific instructions. The Stata Ecinomics Episodes are for the generic lesson that can be reused at any workshop.
