### ISSUE TITLE
Specify directory/subdirectory to use for git 

### ISSUE THREAD

**Issue by ariedamuco** [korenmiklos/2020-08-23-eea#19]
Are we still planning to work in dc-economics-data for git lessons?

**Comment by ariedamuco** [comment]
Will learners commit and push the do-file they create in the Stata part? It might be a nice ending to the workshop.

**Comment by korenmiklos** [comment]
This is a great idea. Can we do this without having to modify the git lesson content? Maybe just copy the .do file into the empty/toy repo they have worked with during the git lesson?

**Comment by korenmiklos** [comment]
Let's postpone this, see how we are progressing?

**Comment by korenmiklos** [comment]
Resolved in #33
