### ISSUE TITLE
Update core.editor = nano instructions for Windows

### ISSUE THREAD

**Issue by korenmiklos** [korenmiklos/2020-08-23-eea#23]
Is it nano.exe?

**Comment by andrasvereckei** [comment]
Nano installation is part of the Gitbash installation process. 
The tutorial and the links are both good.

**Comment by korenmiklos** [comment]
ok, but shall we say "nano.exe" in the lesson?

**Comment by andrasvereckei** [comment]
> ok, but shall we say "nano.exe" in the lesson?

If the installation is good, you don't have to. 
The core.editor=nano.exe is automatically in git config.
Git installed nano into "c:\Program Files\Git\usr\bin\nano.exe" 
The email address and the name are the two missing elements what the user have to fill in. 

I already installed Gitbash verison 2.28.0.windows.1 and I don't see any differences from the previous version.
