### ISSUE TITLE
2. Resolve lesson issues

### ISSUE THREAD

**Issue by andrasvereckei** [korenmiklos/2020-08-23-eea#3]

**Comment by korenmiklos** [comment]
@andrasvereckei Please review the issues in the shell-economics and stata-economics repos and flag whichever is a *must fix* given the schedule of the workshop. For example, there may be materials we skip, so no need to fix issues there.

**Comment by andrasvereckei** [comment]
For shell: 
Add word of caution at introduction #15 and Review and change each code example to match econ files in data.zip #3 could be a must fix. I suggest to delete FIXME-s and folders name with koren inside. 
The main build up is ok, the other issues are improvements. 

For Stata: 
I think there is no big logical error in the material. All the issues are improvements. 
There is a bug in episode 4 but we skip EP now.
A little bit annoying to start using do file in EP5 than go back to cmd and scalars then in EP6 we use that file what we saved in the beginning of EP5. 
I think at the start of EP6 we have to repeat how to make gdp_per_capita.dta. 
An other option that the last challenge at the end of EP5 is a must of.

**Comment by korenmiklos** [comment]
Any remaining errors will be resolved later.
