### ISSUE TITLE
Create pairwise GitHub exercise

### ISSUE THREAD

**Issue by korenmiklos** [korenmiklos/2020-08-23-eea#30]
Practice pushing/pulling from the same repo

**Comment by korenmiklos** [comment]
Will be added here https://docs.google.com/document/d/1q0iYEjvCnDmj8D-PlOpGHg214Sfq8HO4aS7bwTYJhS4/edit?usp=sharing

**Comment by korenmiklos** [comment]
[co-instructor: after the instructor explained the exercise, you will have to create random breakout rooms of 2 people]

[instructor: show some of the steps first on the screen, at least until step 2]

1. You will be working in pairs. One is a repository owner, the other is a collaborator. Discuss who will start as owner and share your GitHub account names.
2. The owner gives Write access rights to the collaborator to their “conversion” repo on GitHub.
3. The collaborator clones the owner’s repo on their local computer.
4. The collaborator edits README.md in nano and adds a line of explanation. They add, commit and push the change.
5. The owner reviews the change on GitHub. They then pull it on their local computer.
6. Switch roles (and repositories) and repeat.

[after exercise, bring back people from breakout rooms and discuss challenges. they will face conflicts etc] @ariedamuco @kiss-oliver

**Comment by bkmgit** [comment]
Maybe worth updating this exercise in future to use create a pdf out of a paper using LaTeX for example see:
https://github.com/xu-cheng/latex-action
https://github.com/vinay0410/tectonic-action
Possible style files include those from [Econometrica](https://www.e-publications.org/ecta/support/) or the source files for
[Writing Finance papers in LaTeX](http://faculty.haas.berkeley.edu/stanton/texintro/)
